### ISSUE TITLE
tests fails with python3.4

### ISSUE THREAD

**Issue by gfa** [joeyespo/path-and-address#1]
I: pybuild base:170: cd /tmp/buildd/python-path-and-address-1.0.0/.pybuild/pythonX.Y_3.4/build; python3.4 -m unittest discover -v 
path_and_address.tests.test_validation (unittest.loader._FailedTest) ... ERROR
# 
## ERROR: path_and_address.tests.test_validation (unittest.loader._FailedTest)

Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/case.py", line 58, in testPartExecutor
    yield
  File "/usr/lib/python3.4/unittest/case.py", line 577, in run
    testMethod()
  File "/usr/lib/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: path_and_address.tests.test_validation
Traceback (most recent call last):
  File "/usr/lib/python3.4/unittest/loader.py", line 323, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python3.4/unittest/loader.py", line 301, in _get_module_from_name
    __import__(name)
  File "/tmp/buildd/python-path-and-address-1.0.0/.pybuild/pythonX.Y_3.4/build/path_and_address/tests/test_validation.py", line 35, in <module>
    addresses = hostnames + ports + _join_all(hostnames, ports)
TypeError: can only concatenate list (not "map") to list

---

Ran 1 test in 0.000s

**Comment by joeyespo** [comment]
@gfa FYI, just released v1.1.0 with Python 3 support.

Thanks for opening the issue!
